sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Nw4FLCg6f6BNrYvKOGzksnh4me4b/dWnqF/KwPn3MH6jZz1xgb8wU11hI6Zix0IhvkiNHBZQFPdh2jywLBFb29dOaAduRE/9A37cQb8+RaaqOidcccU9nSLcIkh3jFClM2jtZHnuJeBUM6hAvD/lG6MSccWwMxf4/xKgY/FSD6ucqP6cbOF9pLW7MgdBmyZFqbieePm8ZHR/X9Se/NrchENQ0ftJjsT1kIiR3gnjctfaGM86ECsq4OY0DtX6sX7OS7+VMtPcrJXu/RKV8Hijp8SgKm/7HPb727ixYzaIcMxHhzm2ZbPfzo7bC5M/5jhhUQsII3APhr0KZzn7PETntuqDZx/ftpn9AELNj5uPiEIovuxwGV38BORiAcUwkp6GocrHkV/oHkyEV/GUybLKV09gYjMxi4ZJSWIFd+iVz11cHjS7eB26+uMWiTI8OMuj2SOknPZ3M04+4g7e2buUGpqyOCCRRg3YFRKb6t9gCLIITDgwRIWUFVSpmowLDINFAWKqRmmbHnEeuEQCgcA59HzZAfUdBH4RTJ2l+65D3fGXMz0NjcVx8X67mMOFYylzn+otEMF5rAGvoKTjoVSV2yfBJ7KJhCAvar7iad1Uxmmo5soI3JXmsGyOcu7IgmBScwAAGBgiwYQ4hGmn6Yz/g4F++DNMPZullMRKfh9ozKc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/John-Bull-s-Other-Island_3612
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy